repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4  # Use latest version
    hooks:
      - id: gitleaks
        args: ['--verbose', '--redact', '--source=.']
        stages: [commit]
